/*  SWI-Prolog link wrapper
    Generated by SWI-Prolog version 7.2.3
    At 2016-10-24 15:18
    Source context /home/giacomomint/yap-lemur/packages/cplint/lemur/lemur.pl:2529
*/

#include <SWI-Prolog.h>
#ifndef NULL
#define NULL ((void *)0)
#endif



static PL_extension predicates [] =
{
/*{ "name", arity, function, PL_FA_<flags> },*/
  { NULL, 0, NULL, 0 } /* terminator */
};

install_t
install_bddem()
{ PL_load_extensions(predicates);
}
